# Generated by Django 5.2.6 on 2026-04-22 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_dolor_minimo', models.IntegerField(default=1)),
                ('nivel_dolor_maximo', models.IntegerField(default=10)),
                ('texto_recomendacion', models.TextField()),
                ('medicamentos_sugeridos', models.CharField(help_text='Solo venta libre', max_length=200)),
                ('sintoma_relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triaje.sintoma')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('nivel_dolor', models.IntegerField()),
                ('sintoma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='triaje.sintoma')),
            ],
        ),
    ]
