# Generated by Django 6.0 on 2026-04-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triaje', '0002_consejo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacion',
            name='advertencias',
            field=models.TextField(blank=True, default='', help_text='Advertencias de riesgo (Ej: Si el dolor persiste por más de 3 días, acuda a un médico).'),
        ),
    ]
