# Generated by Django 6.0 on 2026-04-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triaje', '0003_recomendacion_advertencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacion',
            name='contraindicaciones',
            field=models.TextField(blank=True, default='', help_text='Casos en los que NO se debe seguir esta recomendación (Ej: No usar en caso de embarazo o hipertensión).'),
        ),
    ]
