# Generated by Django 6.0 on 2026-05-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triaje', '0004_recomendacion_contraindicaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='MitoVerdad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mito', models.CharField(help_text='Ej: Los antibióticos curan el resfriado.', max_length=200)),
                ('verdad', models.CharField(help_text='Ej: Los resfriados son virales, no se tratan con antibióticos.', max_length=200)),
                ('activo', models.BooleanField(default=True, help_text='Desmárcalo si quieres ocultarlo temporalmente de la página web.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mito y Verdad',
                'verbose_name_plural': 'Mitos y Verdades',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
