# Generated by Django 6.0 on 2026-05-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triaje', '0005_mitoverdad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recomendacion',
            name='contraindicaciones',
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='precauciones',
            field=models.TextField(blank=True, default='', help_text='Precauciones a considerar antes de seguir esta recomendación (Ej: Precaución en caso de embarazo o hipertensión).'),
        ),
    ]
