# Generated by Django 6.0 on 2026-05-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triaje', '0006_remove_recomendacion_contraindicaciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicamentoOTC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Paracetamol 500mg', max_length=100)),
                ('para_que_sirve', models.CharField(help_text='Ej: Alivia el dolor leve a moderado y reduce la fiebre.', max_length=200)),
                ('dosis_recomendada', models.CharField(help_text='Ej: 1 comprimido cada 8 horas (Máx. 4 al día).', max_length=200)),
                ('precauciones', models.TextField(blank=True, help_text='Ej: No usar en caso de daño hepático o consumo de alcohol.')),
                ('activo', models.BooleanField(default=True, help_text='Desmárcalo para ocultarlo de la página.')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Medicamento OTC',
                'verbose_name_plural': 'Medicamentos OTC',
                'ordering': ['nombre'],
            },
        ),
    ]
