# Generated by Django 6.0 on 2026-06-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triaje', '0007_medicamentootc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamentootc',
            name='precauciones',
            field=models.TextField(blank=True, help_text='Ej: No usar en caso de daño hepático o consumo de alcohol.', verbose_name='Contraindicaciones'),
        ),
    ]
