# Generated by Django 6.0 on 2026-07-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triaje', '0008_alter_medicamentootc_precauciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoArgolla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quien_paga', models.CharField(choices=[('Feli', 'Feli'), ('Any', 'Any')], max_length=10)),
                ('a_quien', models.CharField(choices=[('Cecilia', 'Cecilia (Joyera)'), ('Andreina', 'Andreina (Mamá)')], max_length=15)),
                ('monto', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nota', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Pago de Argolla',
                'verbose_name_plural': 'Pagos de Argollas',
                'ordering': ['-fecha'],
            },
        ),
    ]
