# Generated by Django 6.0 on 2026-07-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triaje', '0009_pagoargolla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoargolla',
            name='quien_paga',
            field=models.CharField(choices=[('Feli', 'Feli'), ('Any', 'Any'), ('Andreina', 'Andreina (Préstamo)')], max_length=15),
        ),
    ]
